### ISSUE TITLE
dsm - Bonus #1 Tracking Fishing

### ISSUE THREAD

**Issue by DerekMalone** [DerekMalone/ASSIGNMENT-Bear-Watcher#6]
- [ ] Create a button that allows the user to indicate it has just tried to catch a fish.
- [ ] Create a button that allows the user to indicate it has just successfully caught a fish.
- [ ] Add a time stamp to when the bear caught a fish/attempted to catch a fish.
- [ ] Total number of fish caught should be listed.
